name: Test

on:
  push:
    branches:
      - main  

jobs:
  scrape-and-save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' 

      - name: Install requiremts.txt
        run: |
          pip install -r requiremts.txt

      - name: Run Python Script
        run: |
          python app.py --url "https://www.threads.net/@foodnetwork/post/Cw8c9wzvOd2"
